# Generated by Django 3.1.3 on 2020-12-08 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.IntegerField(choices=[(1, 'Home'), (0, 'Shop')], default=0)),
                ('payment_mode', models.IntegerField(choices=[(1, 'Card'), (0, 'Cash')], default=0)),
                ('status', models.IntegerField(choices=[(1, 'Placed'), (2, 'Accepted'), (3, 'Barber En Route'), (4, 'Completed'), (5, 'Declined'), (6, 'Cancelled')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_time', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('requests', models.CharField(blank=True, default='', max_length=500)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('service_fee', models.FloatField(default=0)),
                ('subtotal', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=500)),
                ('short_description', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.FloatField(default=0)),
                ('shop_service', models.BooleanField(default=False)),
                ('home_service', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='service_images/')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('avatar', models.CharField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('last_logged_in_as', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(default='', max_length=500)),
                ('email', models.CharField(default='', max_length=500)),
                ('stripe_id', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('last_logged_in_as', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='dashboard.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee'),
        ),
        migrations.AddField(
            model_name='booking',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop'),
        ),
    ]
