# Generated by Django 3.1.2 on 2020-10-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
