# Generated by Django 3.1.2 on 2020-10-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201008_1946'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=500)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, default='haircut_images/blank.jpg', upload_to='haircut_images/')),
                ('price', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shop')),
            ],
        ),
    ]
