# Generated by Django 3.1.3 on 2020-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.IntegerField(choices=[(0, 'Home'), (1, 'Shop')], default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.IntegerField(choices=[(0, 'Card'), (1, 'Cash')], default=1),
        ),
    ]
