# Generated by Django 3.1.2 on 2020-10-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
