# Generated by Django 3.1.3 on 2020-11-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201115_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_logged_in_as',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_logged_in_as',
            field=models.BooleanField(default=False),
        ),
    ]
