# Generated by Django 3.1.3 on 2020-11-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201105_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.IntegerField(choices=[(1, 'Card'), (0, 'Cash')], default=0),
        ),
    ]
