# Generated by Django 3.1.2 on 2020-10-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_employee_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='verified',
        ),
    ]
