# Generated by Django 3.1.2 on 2020-10-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_customer_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='shop',
        ),
    ]
