# Generated by Django 3.1.2 on 2020-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_employee_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_key',
            field=models.CharField(default='', max_length=500),
        ),
    ]
