# Generated by Django 3.1.2 on 2020-10-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('dashboard', '0004_remove_employee_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.shop'),
        ),
    ]
