# Generated by Django 3.1.2 on 2020-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_employee_employee_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_key',
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
