# Generated by Django 3.1.2 on 2020-10-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20201011_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.IntegerField(choices=[(1, 'Home Booking'), (2, 'Shop Booking')], default=2),
        ),
    ]
