# Generated by Django 3.1.2 on 2020-10-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20201011_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Shop')], default=2),
        ),
    ]
