# Generated by Django 3.1.2 on 2020-10-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_booking_requested_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Placed'), (2, 'Accepted'), (3, 'Barber En Route'), (4, 'Completed'), (5, 'Declined'), (6, 'Cancelled')]),
        ),
    ]
