# Generated by Django 3.1.2 on 2020-10-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20201012_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
