# Generated by Django 3.1.2 on 2020-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20201012_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requested_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
