# Generated by Django 3.1.2 on 2020-10-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20201013_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requests',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
