# Generated by Django 3.1.2 on 2020-10-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
