# Generated by Django 3.1.3 on 2020-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='visible_on_app',
            field=models.BooleanField(default=False),
        ),
    ]
