# Generated by Django 3.1.2 on 2020-10-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='fb',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='ig',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
