# Generated by Django 3.1.2 on 2020-10-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='home_bookings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_bookings',
            field=models.BooleanField(default=False),
        ),
    ]
