# Generated by Django 3.1.2 on 2020-10-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201027_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(upload_to='shop_logo/'),
        ),
    ]
