# Generated by Django 3.1.2 on 2020-10-18 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201018_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='ig',
            new_name='instagram',
        ),
    ]
