# Generated by Django 3.1.5 on 2021-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_shop_visible_on_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='service_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
