# Generated by Django 3.1.2 on 2020-10-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201018_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='facebook',
        ),
    ]
